### ISSUE TITLE
Problem on client load

### ISSUE THREAD

**Issue by Weefle** [ME1312/SubServers-2#1]
Hello I'm french and I have a problem on client's load: https://hastebin.com/ahesiboraz.css
I'm sure I have configured everything!
Please help me, maybe it's a bug, here, you can see all of my terminal: https://hastebin.com/etozurohus.erl
Thanks.

**Comment by ME1312** [comment]
Translating tells me this error is caused by windows protecting the config from being overwritten by the config updater. Make sure nothing else is using the config file or just rename/delete it yourself.
