### ISSUE TITLE
[Feature Request] Control the sub servers from your pc

### ISSUE THREAD

**Issue by amit177** [ME1312/SubServers-2#11]
Hey,
I think that you should add another version of SubServers,
which you can run on your pc, and control the host with it.
It would help instead of logging in to the server everytime to execute a command or start/stop it.

Thanks,
Amit

**Comment by ME1312** [comment]
If this is going to (officially) be made, it'd have to be made right: and I'm not the guy to do it.

Unfortunately my knowledge of writing actual apps (not just command line ones) is quite limited. I have a vision for what a companion app for SubServers should  look like though.

For now, this will remain unresolved.
