### ISSUE TITLE
The /end command doesn't work

### ISSUE THREAD

**Issue by amit177** [ME1312/SubServers-2#15]
Hey,
For some reason the "end" command won't work for me.
I'm running 11 sub servers.
it always ends up where I have to kill the servers from the ssh(which is bad for them).

Screenshot:
http://cdn.amit177.cf/2017-08-27_12-11-06.png

**Comment by ME1312** [comment]
The problem here is that SubServers tries to stop each server via command. If one of your servers is frozen (or isn't accepting commands for whatever reason) it causes it to hang. Let me see the server config

**Comment by amit177** [comment]
You mean subservers's config.yml?

**Comment by ME1312** [comment]
yup

**Comment by amit177** [comment]
https://hastebin.com/ijelixicad.sql

Ignore the server names and the directories

**Comment by ME1312** [comment]
I'm not really sure here...

**Comment by amit177** [comment]
Oh and SubServers-Client-Bukkit always trying to link it self twice for some reason.
(I checked all of the servers, the name is only in one server)
when you join the server subservers-client-bukkit is disabled, and in the logs it says

> "The SubData Connection was closed"
"Attempting to reconnect in 30 seconds"
**30 seconds later**
"Lang Settings Downloaded"
"Could not link name with server: Server already linked"
"The SubData Connection was closed"

this one happends in all of the servers.

**Comment by amit177** [comment]
Also I for some reason the subapi won't send the command to the subserver.
Code:
`SubAPI.getInstance().getSubServer("Hub").command("say test");`


SubServers log:
`15:10:04 [WARNING] Event net.ME1312.SubServers.Bungee.Event.SubSendCommandEvent@2fcd788b took 1,156,403,641ns to process!`

Shows like it was sent, but nothing happends in the game.

**Comment by ME1312** [comment]
These issues don't show themselves in my tests, so I really can't be of any help here since I've got no leads. On that last one, perhaps the event was cancelled.

**Comment by amit177** [comment]
Any idea how to check if it was cancelled? and if you want I can give you the ip and show you.

**Comment by ME1312** [comment]
Closed until there is any more information on this issue
