### ISSUE TITLE
SubServers Console don't work with command /popouts <subservers>

### ISSUE THREAD

**Issue by CanardConfit** [ME1312/SubServers-2#16]
Version of SubServers : 2.12.1f
Explication : On start subservers, thisplugins sent "Enabled plugin SubServers-Console version 2.12b by ME1312", this is normal, and i write /popouts test1 (test1 is a subserver) and this not work...

Error on /popouts : 

>popouts test1
14:42:35 [GRAVE] Exception in thread "main"
14:42:35 [GRAVE] java.lang.IncompatibleClassChangeError: Found interface net.ME1312.SubServers.Bungee.Host.SubServer, but class was expected
14:42:35 [GRAVE]      at net.ME1312.SubServers.Console.PopoutCommand$SERVER.execute(PopoutCommand.java:33)
14:42:35 [GRAVE]      at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
14:42:35 [GRAVE]      at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
14:42:35 [GRAVE]      at net.ME1312.SubServers.Bungee.Launch.main(Launch.java:94)

PS: I am not English, I am French, my English is not very correct :)

CanardConfit

**Comment by ME1312** [comment]
Fixed as of 2.12.1a
