### ISSUE TITLE
Server starting error...

### ISSUE THREAD

**Issue by gabe56f** [ME1312/SubServers-2#18]
### App Info:
**App Name: SubsServer-Bungee**
<br>**App Version: LATEST**
<br>**Minecraft Version: 1.8-1.12.2**
### Issue:
*at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
at net.ME1312.SubServers.Bungee.Launch.main(Launch.java:88)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 17 more
[m[2K 15:27:50 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
[m[2K 15:27:50 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
[m[2K 15:27:50 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
[m[2K 15:27:50 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
[m[2K 15:27:50 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
[m[2K 15:27:50 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
[m[2K 15:27:50 [SEVERE] Exception in thread "main" 
[m[2K 15:27:50 [SEVERE] java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
[m[2K 15:27:50 [SEVERE] at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:244)
[m[2K 15:27:50 [SEVERE] at net.md_5.bungee.conf.Configuration.load(Configuration.java:79)
[m[2K 15:27:50 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:269)
[m[2K 15:27:50 [SEVERE] at net.ME1312.SubServers.Bungee.Launch.main(Launch.java:88)
[m

I get this error when i try to launch my server...*

**Comment by ME1312** [comment]
It looks like there's a yaml problem in `~/config.yml` (something is a yaml list where a yaml object is required)
