### ISSUE TITLE
Bungeecord Startup Error

### ISSUE THREAD

**Issue by Rainbwz** [ME1312/SubServers-2#19]
### App Info:
**App Name: SubServers.Bungee**
<br>**App Version: 2.11.2a+**
<br>**Minecraft Version: 1.12.2**
### Issue:
Hi, I'm currently having an issue with this plugin. It seems to be working fine on my server and I have created some SubServers with it but it seems that whenever I add them in to the config.yml of the SubServers folder then I get this error.
Error:
16.03 18:35:27 [Server] INFO SubServers > Hub has stopped
16.03 18:35:27 [Server] SEVERE ... 5 more
16.03 18:35:27 [Server] SEVERE at java.lang.ProcessImpl.start(Unknown Source)
16.03 18:35:27 [Server] SEVERE at java.lang.UNIXProcess.<init>(Unknown Source)
16.03 18:35:27 [Server] SEVERE at java.lang.UNIXProcess.forkAndExec(Native Method)
16.03 18:35:27 [Server] SEVERE Caused by: java.io.IOException: error=2, No such file or directory
16.03 18:35:27 [Server] SEVERE at java.lang.Thread.run(Unknown Source)
16.03 18:35:27 [Server] SEVERE at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubServer.run(InternalSubServer.java:103)
16.03 18:35:27 [Server] SEVERE at java.lang.Runtime.exec(Unknown Source)
16.03 18:35:27 [Server] SEVERE at java.lang.Runtime.exec(Unknown Source)
16.03 18:35:27 [Server] SEVERE at java.lang.ProcessBuilder.start(Unknown Source)
16.03 18:35:27 [Server] SEVERE java.io.IOException: Cannot run program "java" (in directory "./../Hub"): error=2, No such file or directory
Setup in config.yml:
Servers:
  'Hub':
    Enabled: true
    Display: ''
    Host: '~'
    Group: []
    Port: 25567
    Motd: '&aThis is a SubServer'
    Log: true
    Directory: '../Hub'
    Executable: 'java -Djline.terminal=jline.UnsupportedTerminal -jar Spigot.jar'
    Stop-Command: 'stop'
    Run-On-Launch: false
    Auto-Restart: false
    Restricted: false
    Incompatible: []
    Hidden: false

Thank you for your time. I hope you can give me some insight into what is going on but I never remembered having this issue.

**Comment by ME1312** [comment]
It is probably an issue regarding relative paths.

Did you intend it to attempt to find this folder?
```
> <parent directory>
--> Hub (this is what it reportedly cannot find)
----> <server files>
--> <app launch directory>
----> SubServers
------> config.yml
```

**Comment by Rainbwz** [comment]
I don't understand what you mean but I meant for it to find the folder called Hub. I think I understand what you're getting at but if you could explain it to me that would be great.

**Comment by ME1312** [comment]
Basically, what I'm getting at is the placement of this "Hub" folder. Based on the error and config I made up a little graph in the last post. The directory in question is `./../Hub`:
1. Relative paths should all start from your `<app launch directory>`
2. The `./` at the beginning comes from your host `~`'s directory, which points to the current directory, which is: `<app launch directory>`
3. The `../Hub` is the directory you entered, which points to the parent directory, then to one named `Hub`

This would place your folder here in the real world:
![](https://s17.postimg.org/e89g0xxlb/Capture.png)

**Comment by Rainbwz** [comment]
Oh alright. I intended to have it detect the Hub folder inside the bungeecord server folder. Do you know the correct format to have it pick up the Hub folder which is out of the SubServers folder and in the bungeecord one?

**Comment by ME1312** [comment]
For that, the correct format would be `./Hub` (which points to the current directory, which is still `<app launch directory>` as set by step 2 in the previous post, then to one named `Hub`)

**Comment by Rainbwz** [comment]
Okay. Thank you so much for your help. I really enjoy your plugin and it’s amazing that you were able to create this.
