### ISSUE TITLE
Possibly just Windows issue

### ISSUE THREAD

**Issue by Lmmb74** [ME1312/SubServers-2#2]
Every time I try to create a SubServer, the process stops just after building the jars. Nothing happens after that, even though it has to copy the server jar and start it.

**Comment by Lmmb74** [comment]
Just checked and seems like it does not even finish compilation :/.

**Comment by ME1312** [comment]
Can you perhaps attach the subcreator log file? I may have to report this to the spigot team since I've seen multiple reports and been able to reproduce this issue on windows.

**Comment by Lmmb74** [comment]
[SubCreator-SPIGOT-1.8.8.txt](https://github.com/ME1312/SubServers-2/files/676025/SubCreator-SPIGOT-1.8.8.txt)
Had to change its file extension due to github not supporting log files.

**Comment by ME1312** [comment]
Yeah it looks to be that same "BuildTools Freezing" issue. I've gone ahead and [reported it to them.](https://hub.spigotmc.org/jira/browse/BUILDTOOLS-295)

**Comment by Lmmb74** [comment]
Kk thanks :D

**Comment by Lmmb74** [comment]
Gotta tell you that I do not have this problem when I am not using SubServers. So I think the problem is not BuildTools itself.

**Comment by ME1312** [comment]
There's no other explanation really, I've followed all the launch requirements:
• Require Java 8
• Downloading the latest BuildTools version
• Launching in Git Bash
• Giving BuildTools/Maven the proper amount of RAM

Theres no mention of buildtools just freezing [in the wiki](https://www.spigotmc.org/wiki/buildtools/#issues-and-common-concerns).

**Comment by Lmmb74** [comment]
Kk

**Comment by ME1312** [comment]
Not sure how I never noticed this before, but SubConsole wasn't handling the ErrorStream at all. Apparently this is what caused buildtools to freeze (not sure how). It's been corrected now though.
