### ISSUE TITLE
can't build servers in linux

### ISSUE THREAD

**Issue by compieter-gh** [ME1312/SubServers-2#22]
### Platform Information
operating system: ubuntu 18.04
openjdk 10.0.1 2018-04-17
latest dev build 18w30bi

### What Happened
i get an error when trying to build a server

### How It Happened
i was going to make a test server

### Additional Information
can't reproduce this problem on windows 10 and on an older version 2.12.1f

it aplies to spigot,forge,spong,vanilla

**Comment by ME1312** [comment]
This issue does not show up in my tests. Although I have been changing the back-end of my build distribution that should have no effect on Buildtools, Sponge, or Forge servers. Even though you said it didn't happen before, please make sure your machine meets the [requirements of SubServers.](https://github.com/ME1312/SubServers-2/wiki/Install#prerequisites)

**Comment by compieter-gh** [comment]
i finally figured it out after hours of trying it was wget
but please look into wget there is something wrong with it i think
the solution now is curl

it was frustrated
