### ISSUE TITLE
bungeecord forced hosts

### ISSUE THREAD

**Issue by mineblow** [ME1312/SubServers-2#23]
### What Should Be Added
be able to add forced hosts without having to edit the bungeecord conf.yml

### What's The Alternative
editing the bungeecord.yml and restarting the proxy

**Comment by BrightSkyz** [comment]
I talked to @ME1312 about this, he said he wasn't going to do this -- you could use the API and have a plugin that when enabled, it will send a message to the main host and that will return an array with the forced hosts and you can then dynamically add them to bungeecord.

**Comment by mineblow** [comment]
Ok, thanks
