### ISSUE TITLE
Connection Timed Out

### ISSUE THREAD

**Issue by jphuse** [ME1312/SubServers-2#24]
### Platform Information
Used Latest SubServers-Bungee, Latest SubServers-Client-Bukkit, Latest SubServers-Console

### What Happened
I don't see any errors; however, I can't seem to connect to my server. It says it's up and all of the servers seem to be up, but I get "Connection Timed Out" when I'm attempting to connect to the server.

### How It Happened
I started the server, tried to join it.

### Additional Information
Here is my SubServers config.yml file: https://hastebin.com/hilugitave.js

**Comment by ME1312** [comment]
SubServers definitely isn't the root of your issue when it comes to messages like "Timed Out." Check your other plugins to see if they could be stalling your server's main thread.
