### ISSUE TITLE
Autorestart option

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#26]
### What Should Be Added
A per server configuration option that dis-/enables autorestart if the server got stopped or crashed (Useful for Minigames)

### Why It Should be Added
Useful for many minigames that stops a server after a finished game.

### What's The Alternative
Don't know...

**Comment by ME1312** [comment]
What about `Stop-Action: RESTART`? (triggered by `/stop`, crashes, etc)

**Comment by xXSchrandXx** [comment]
My bad, didn't saw that...
