### ISSUE TITLE
cache not working 2.13.2b

### ISSUE THREAD

**Issue by compieter-gh** [ME1312/SubServers-2#29]
when i build a server it doesn't cache it makes the folders but it does not copy the file.
if you need any more info just say it.

**Comment by ME1312** [comment]
I think I'm gonna say it. `/sub version` in console and SubCreator's log file would be useful

**Comment by compieter-gh** [comment]
Ok 

02:32:49 [INFO] SubServers > These are the platforms and versions that are running SubServers.Bungee:
02:32:49 [INFO]   Linux 4.15.0-43-generic [x64],
02:32:49 [INFO]   Java 1.8.0_191 [x64],
02:32:49 [INFO]   BungeeCord git:BungeeCord-Bootstrap:1.13-SNAPSHOT:9a2acc8:1390,
02:32:49 [INFO]   SubServers.Bungee v2.13.2b (18w51b)
02:32:49 [INFO]
02:32:49 [INFO] You are on the latest version.


[SubCreator-Spigot-1.13.2.log](https://github.com/ME1312/SubServers-2/files/2725787/SubCreator-Spigot-1.13.2.log)

edit: one thing to note is that the cache folder is being created when building the jar
and then be deleted again when finished.

**Comment by ME1312** [comment]
> the cache folder is being created when building the jar and then be deleted again when finished

This is common when the cache directory is requested but goes unused by SubCreator's scripts. If it went unused, that means bash couldn't find it. This latest snapshot should address that concern.

If that doesn't work, I've got some more questions:
-> Do you have any symbols/spaces in the directory path?
-> Does SubServers have the correct file permissions to address it's own caches? (this one's a stretch)

**Comment by compieter-gh** [comment]
still having the problem with the new build but when i try it with 2.13.2b it works fine now.
it definitely was a path issue.

"/mnt/911e0d2d-6cdd-4666-8cf5-2e93456e7950/Minecraft Servers/SubServers_2" this was my server path

"/mnt/911e0d2d-6cdd-4666-8cf5-2e93456e7950/Minecraft_Servers/SubServers_2" this is now my server path

**Comment by ME1312** [comment]
Seems I broke it huh? Well, I guess it has to get worse before it gets better. It turns out multi-platform command line escaping is pretty hard the deeper you get.

Spaces should be supported because the character is a common one (even though it can be frustrating). This latest build (19w01d) should fix what I broke and re-add support for spaces on linux in one go.

**Comment by compieter-gh** [comment]
yeah hahaha, i'll test it.

**Comment by compieter-gh** [comment]
another bug when i type in the console i get an stack trace:
and then i cant type anymore.

23:04:41 [SEVERE] Exception in thread "main"
23:04:41 [SEVERE] java.io.IOException: Invoer-/uitvoerfout
23:04:41 [SEVERE]     at java.io.FileInputStream.read0(Native Method)
23:04:41 [SEVERE]     at java.io.FileInputStream.read(FileInputStream.java:207)
23:04:41 [SEVERE]     at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
23:04:41 [SEVERE]     at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
23:04:41 [SEVERE]     at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
23:04:41 [SEVERE]     at jline.internal.InputStreamReader.read(InputStreamReader.java:261)
23:04:41 [SEVERE]     at jline.internal.InputStreamReader.read(InputStreamReader.java:198)
23:04:41 [SEVERE]     at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145)
23:04:41 [SEVERE]     at jline.console.ConsoleReader.readLine(ConsoleReader.java:2349)
23:04:41 [SEVERE]     at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
23:04:41 [SEVERE]     at net.ME1312.SubServers.Bungee.Launch.main(Launch.java:129)

**Comment by DuckCaller** [comment]
Stop spamming my email notifications kthx

**Comment by ME1312** [comment]
> another bug when i type in the console i get an stack trace:
> and then i cant type anymore.

Is that just a one-off issue? If it happens to you every time, is there any sort of instruction so that I may see that for myself?

**Comment by compieter-gh** [comment]
yeah just start subservers and when you try to type it wil crash
it's happening every time i start it

**Comment by ME1312** [comment]
As ridiculous as this is, that issue was caused by the `-i` option in a child process interfering with the parent's terminal. That option has been removed.

(btw, this issue manifested itself in a `[1]+  Stopped` issue on my end)

**Comment by compieter-gh** [comment]
ok everything is working fine i tested it and the isseus has been resolved thanks for your time.
