### ISSUE TITLE
Only one Server

### ISSUE THREAD

**Issue by kenkrelous** [ME1312/SubServers-2#3]
Hello 
I have a problem with your plugin , when I send the command "sub" to my bungeecord , he reload him.
So my server or reboot .
So that all , and thank you to take time to read me !

Ps: Sorry for my english , I am french :)
Kenkrelous

**Comment by ME1312** [comment]
Sorry, I don't understand the problem (could you perhaps retype that, or show the problem?)

**Comment by ME1312** [comment]
Closed until clarified
