### ISSUE TITLE
Softlinked folder recursive deletion mistake

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#32]
### Platform Information
` RageBears - Minecraft git:BungeeCord-Bootstrap:1.13-SNAPSHOT:854fd13:224, SubServers.Bungee v2.13.2c (19w03a)`

### What Happened
With `sub delete <SubServer>`, the files in softlinked folders are getting deleted, softlined files not. Can you change the Recoursive deleting for softlinks to false?

### How It Happened

1. Creating a Server with softlinks (`ln -s $pluginfoldername $sharedfolderpath`)
2. Delete the server with `sub delete <SubServer>`
3. Check in `$sharedfolderpath` for deleted files

### Additional Information
Maybe add [Files.isSymbolicLink(link)](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#isSymbolicLink(java.nio.file.Path)) in your [Utils](https://github.com/ME1312/SubServers-2/blob/df159f72fe3859a7de4add513987141f45bcc700/SubServers.Bungee/src/net/ME1312/SubServers/Bungee/Library/Util.java#L173).
``` Java
            for(File f: files) {
                if (Files.isSymbolicLink(f) {
                  Files.delete(f);
                }
                else if(f.isDirectory()) {
                    deleteDirectory(f);
                } else {
                    f.delete();
                }
              }
```

**Comment by xXSchrandXx** [comment]
Same in Java 8 https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#isSymbolicLink-java.nio.file.Path-

**Comment by ME1312** [comment]
Even though what happened is technically correct, it must have been frustrating. This behavior has been adjusted.

If you haven't found them already, you can find a copy of those deleted files in the `Recently Deleted` folder
