### ISSUE TITLE
Nothing else than ProxiedPlayer and ConsoleCommandSender

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#33]
### Platform Information
RageBears - Minecraft git:BungeeCord-Bootstrap:1.13-SNAPSHOT:854fd13:224,
SubServers.Bungee v2.13.2c (19w03d)

### What Happened
Using my BungeeRcon I do `get java.lang.ClassCastException: bungee.api.rcon.RconCommandSender cannot be cast to net.md_5.bungee.api.connection.ProxiedPlayer`

RconCommandSender:
``` Java
package bungee.api.rcon;

import java.util.ArrayList;
import java.util.Collection;
import net.md_5.bungee.api.CommandSender;
import net.md_5.bungee.api.ProxyServer;
import net.md_5.bungee.api.chat.BaseComponent;

public class RconCommandSender implements CommandSender
{
  private final StringBuffer buffer = new StringBuffer();
  private final ProxyServer server;
  
  public RconCommandSender(ProxyServer server)
  {
    this.server = server;
  }
  
  public ProxyServer getServer()
  {
    return this.server;
  }
  
  public String flush()
  {
    String result = this.buffer.toString();
    this.buffer.setLength(0);
    return result;
  }
  
  public String getName()
  {
    return "Rcon";
  }
  
  public void sendMessage(String message)
  {
    this.buffer.append(message).append("\n");
  }
  
  public void sendMessages(String... messages)
  {
    for (String line : messages) {
      sendMessage(line);
    }
  }
  
  public void sendMessage(BaseComponent... message)
  {
    for (BaseComponent line : message) {
      sendMessage(line);
    }
  }
  
  public void sendMessage(BaseComponent message)
  {
    sendMessage(message.toLegacyText());
  }
  
  public Collection<String> getGroups()
  {
    return new ArrayList<String>();
  }
  
  public void addGroups(String... groups) {}
  
  public void removeGroups(String... groups) {}
  
  public boolean hasPermission(String permission)
  {
    return true;
  }
  
  public void setPermission(String permission, boolean value) {}
  
  public Collection<String> getPermissions()
  {
    return new ArrayList<String>();
  }
}
```

### How It Happened
Using my Rcon with command sub causes a Error in [net.ME1312.SubServers.Bungee.SubCommand.execute](https://github.com/ME1312/SubServers-2/blob/118ac28e4c170949f0e49271738a531d181bcf4c/SubServers.Bungee/src/net/ME1312/SubServers/Bungee/SubCommand.java#L605). Caused because RconCommandSender can't be ProxiedPlayer, so could you maybe remove the ConsoleCommandSender check (or add a funktion for instances wich are just CommandSender?)

### Additional Information
Or can you discribe me how I can change that in my own .java?

**Comment by ME1312** [comment]
Should be okay to continue with that now. SubServers already sends command response messages through the proper channels, so you shouldn't get anything strange.
