### ISSUE TITLE
Console switching

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#34]
### What Should Be Added
A command to switch between bungeecord and minecraftserver consoles.
`sub showconsole <SubServer | BungeeCord>` for entering or switching between SubServers | BungeeCord.

### Why It Should be Added
Could be useful to get direct feedback from a server (no need to change Logs to true) and reload subservers or to look up the different logs of the minecraft servers.
Could be useful to send commands without `sub cmd <SubServer> <Command> [Args...]` direct to the console of a SubServer (and see the feedback for the command).

### What's The Alternative
Using the configs `Logs` feature and `sub cmd`.

**Comment by ME1312** [comment]
`/sub sudo|screen <SubServer>` exists in SubServers.Bungee already, but it has remained console-only for now. Although it doesn't have enough power to suppress BungeeCord's own messages, it does suppress the messages of other servers while overriding the server's own `log` option.

A more extreme version of this feature can be added by the SubServers.Console plugin; which can pop out individual servers' log messages into their own console window entirely.

**Comment by xXSchrandXx** [comment]
`/sub sudo|screen <SubServer>` is alredy what I wanted, but the feedback of the server the user connected with would be great.

**Comment by ME1312** [comment]
Ah, I see. Right now it is not overriding that option even though it should be.
