### ISSUE TITLE
Adding templates setting variables to servers executable setting

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#35]
### What Should Be Added
Add the variables like [build.sh's](https://github.com/ME1312/SubServers-2/wiki/SubCreator) to the [Executable Setting](https://github.com/ME1312/SubServers-2/wiki/Configuration)
``` BASH
$name (used for paths or '-w $name' to change the default world)
$port ('-p $port' to set port without changing server.properties)
```
And link javas, minecrafts, [spigots](https://www.spigotmc.org/wiki/start-up-parameters/), forges and papers start up parameter.

### Why It Should be Added
Useful to enchant the performance and file managing for bigger networks.

### What's The Alternative
Don't know...

**Comment by ME1312** [comment]
There isn't all that much that could be useful as a variable available to [the hosts themselves](https://github.com/ME1312/SubServers-2/blob/master/SubServers.Host/src/net/ME1312/SubServers/Host/Executable/SubServer.java#L23-L37), but `name` and `port` have been added.

EDIT: `address` is also available now. (for use with the `--host` spigot option, for example)
