### ISSUE TITLE
No reload

### ISSUE THREAD

**Issue by U-siro** [ME1312/SubServers-2#4]
I need the reload because I need to update config.yml file.
Please make it!

**Comment by ME1312** [comment]
SubServers (and SubAPI) reloads with BungeeCord's /greload

**Comment by U-siro** [comment]
I see, but if I use /greload, It will restart all subservers.

**Comment by ME1312** [comment]
SubServers (1) had that command, and it did the same thing. The servers must be stopped to reload the config because your discarding the old host & server configuration for a new one.

**Comment by U-siro** [comment]
Can you make to avoid this problem? e.g: Not changed host & server is not turned off.

**Comment by ME1312** [comment]
That kind of defeats the purpose of the command. Your asking for a [reload](https://google.com/search?q=define+reload), so reloading SubServers (Add-On) will reload the servers as well.

**Comment by ME1312** [comment]
This issue has been resolved as of the [latest commit](https://github.com/ME1312/SubServers-2/commit/0bf5f16e09b9153187f76ceb769c784b54af1117)
