### ISSUE TITLE
SubServer sorted startup

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#42]
### What Should Be Added

- A config option to set a max of starting SubServers (per host or total)
- A config option to set a startup priority (highest priority does start first)

If a server got defined as SubServer: something, the next does start.

### Why It Should be Added
It should be added because on some servers the CPU utilization is on 100% when multiple SubServers are starting up...

**Comment by ME1312** [comment]
This sort of already exists. Have you tried the [`Run-On-Launch-Timeout` option](https://github.com/ME1312/SubServers-2/wiki/Configuration#subserversconfigyml-global-configuration)?

As for priority, at the moment they should be started in the order they appear in `config.yml`

**Comment by xXSchrandXx** [comment]
Doesn't the Timeout just affect the SubData connection?

I want to start 2 servers completely until the next 2 are allowed to start.

**Comment by ME1312** [comment]
Nah, You might have been thinking of `Reconnect` (which uses similar time formatting)

`Run-On-Launch-Timeout` is the time in seconds the auto-start thread should wait before starting the next server. If the server in question connects to SubData at any point during that time the remaining time will be skipped.
