### ISSUE TITLE
making a custom paper template but failing

### ISSUE THREAD

**Issue by compieter-gh** [ME1312/SubServers-2#47]
this is the error i got
[Paper.zip](https://github.com/ME1312/SubServers-2/files/3292592/Paper.zip)

00:52:51 [INFO] SubServers > These are the platforms and versions that are running SubServers.Bungee:
00:52:51 [INFO]   Linux 4.15.0-51-generic [x64],
00:52:51 [INFO]   Java 1.8.0_212 [x64],
00:52:51 [INFO]   BungeeCord git:BungeeCord-Bootstrap:1.14-SNAPSHOT:8fda060:1413,
00:52:51 [INFO]   SubServers.Bungee v2.13.2d (19w17a)
00:52:51 [INFO]
00:52:51 [INFO] You are on the latest version.

00:50:11 [INFO] ~/Creator > Couldn't load template: Paper
00:50:11 [SEVERE] java.lang.IllegalArgumentException: No enum constant net.ME1312.SubServers.Bungee.Host.SubCreator.ServerType.PAPER
00:50:11 [SEVERE]     at java.lang.Enum.valueOf(Enum.java:238)
00:50:11 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.SubCreator$ServerType.valueOf(SubCreator.java:164)
00:50:11 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.SubCreator$ServerTemplate.<init>(SubCreator.java:45)
00:50:11 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubCreator.reload(InternalSubCreator.java:291)
00:50:11 [SEVERE]     at net.ME1312.SubServers.Bungee.SubCommand.execute(SubCommand.java:149)
00:50:11 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:189)
00:50:11 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142)
00:50:11 [SEVERE]     at net.ME1312.SubServers.Bungee.Launch.main(Launch.java:131)

**Comment by compieter-gh** [comment]
facepalm just fixed it it was the fucking server type that has to be on custom

**Comment by compieter-gh** [comment]
also can't set the setting for query.port=

**Comment by ME1312** [comment]
Yes, the `SPIGOT` or `CUSTOM` server types should work well with Paper.

As for the vanilla query feature, I had only noticed recently that the default templates had this enabled now that 1.14 shows a proper debug message for it. Put simply, that query feature just doesn't mesh well with BungeeCord and it typically always goes unused anyway.

As such, the default `server.properties` now disables query. I suggest that you disable it in templates as well.

**Comment by compieter-gh** [comment]
also can there be an way too update subservers spigot/forge/etc versions with a command like /sub update [server] {server type] [version] that redownloads/builds the newest spigot/etc versions and then overwrite the original one this would be really nice because spigot/paper are always updateing there latest server jars with fixes and other stuff

**Comment by ME1312** [comment]
That feature is still on the list of potential ones for me to add. Although, you are right: it's more relevant now then ever.

Since I feel like I have to mention this again, Paper was not included (by default) in SubCreator because they do not have a standardized machine-readable versioning system, and when I told them about this they didn't seem too keen on making one.

**Comment by compieter-gh** [comment]
that was maby also why my deluxemenu didn't work with waterfall/tavertine on subservers
it works on a normal setup tho
