### ISSUE TITLE
Cannot create a server

### ISSUE THREAD

**Issue by baibeebambi** [ME1312/SubServers-2#48]
### Platform Information
`17:24:08 [INFO] SubServers > These are the platforms and versions that are running SubServers.Bungee:`
`17:24:08 [INFO]   Windows 10 [x64],`
`17:24:08 [INFO]   Java 1.8.0_221 [x86],`
`17:24:08 [INFO]   BungeeCord git:BungeeCord-Bootstrap:1.14-SNAPSHOT:9e76966:1420,`
`17:24:08 [INFO]   SubServers.Bungee v2.14.4a (19w39b)`
`17:24:08 [INFO]`
`17:24:08 [INFO] You are on the latest version.`

### What Happened
`>sub create Test ~ Spigot 1.14.4 17263`
`17:16:22 [INFO] Test\Creator > Loading Template: Spigot`
`17:16:22 [INFO] Test\Creator > Launching Build Script...`
`17:16:22 [INFO] Test\Creator > The system cannot find the path specified.`
`17:16:23 [INFO] Test\Creator > Couldn't build the server jar. Check the SubCreator logs for more detail.`

### How It Happened
I had gone ahead and tried creating a sub server inside of the Proxy Terminal and I get the errors stated above.

#### Log File:
`---------- LOG START — Cine\Creator ----------`
`The system cannot find the path specified.`
`------------------ LOG END ------------------`
`------------------ LOG END ------------------`

**Comment by baibeebambi** [comment]
### Resolved!

**Comment by ME1312** [comment]
This type of issue can happen when either or both of these things are happening:
* Your machine does not currently meet [the requirements of SubServers](https://github.com/ME1312/SubServers-2/wiki/Install#requirements)
* The executable file specified by the template is not available where it should be
