### ISSUE TITLE
Auto install plugins when creating a server.

### ISSUE THREAD

**Issue by Dycool** [ME1312/SubServers-2#55]
### What Should Be Added
When someone is creating a server, the plugins that are on the config should be placed on the server.

### Why It Should be Added
I think this should be added because it will be easier to create hubs.

### What's The Alternative
The alternative is to put all the plugins each time you create a server.

**Comment by BasToTheMax** [comment]
Why close this?

**Comment by Alex1607** [comment]
> Why close this?

This already exists in SubServers, just add the plugins into the plugins folder of the template server :)

**Comment by BasToTheMax** [comment]
oh oke
