### ISSUE TITLE
Compatibility issue with MiniMotd

### ISSUE THREAD

**Issue by wysohn** [ME1312/SubServers-2#56]
### Platform Information
13:11:01 [INFO]   Linux 4.15.0-122-generic [x64],
13:11:01 [INFO]   Java 1.8.0_272 [x64],
13:11:01 [INFO]   BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539,
13:11:01 [INFO]   SubServers.Bungee v2.16a (20w26d)
13:11:01 [INFO]
13:11:01 [INFO] You are on the latest version.

### What Happened
We've recently found [this](https://www.spigotmc.org/resources/minimotd-server-list-motd-plugin-with-rgb-gradients.81254/) plugin, which shows some fancy RGB motd, yet using this with SubServers, it doesn't work.

All I can see is the message, Cannot connect to the server, yet I still can connect to server without problem. Does SubServer has something to do with the motd packet?

The plugin works without problem if I start the bungeecord directly, but problem happens when I use it indirectly through SubServer.

### How It Happened
Drop the [plugin](https://www.spigotmc.org/resources/minimotd-server-list-motd-plugin-with-rgb-gradients.81254/) in the plugins folder

**Comment by ME1312** [comment]
To be frank, I'm not really sure what's going on here. Something appears to be failing silently.

SubServers does not alter the implementation of BungeeCord packets. As for the MOTDs themselves, while there are a few scenarios where SubServers will provide its own MOTD, there is plenty of room for plugins to serve their modifications. ServerListPlus is a good example of such functionality.

**Comment by wysohn** [comment]
Well, that's why I conducted an experiment excluding all plugins, except the MiniMotd because at first, I suspected other plugin interfering with the Motd. However, I had no luck finding out what's going on either. It's very strange since I don't really see some straight forward reason why this is happening.

Have you tried the plugin yourself? If it actually works in your environment, then it sounds like I have some configuration that I am not aware of is causing the problem. But as far as I tested, it doesn't happen with the bungeecord itself, but it happens when I used it with SubServers.

Many thanks!

**Comment by ME1312** [comment]
I was able to replicate this issue on the test network. Interestingly, SubServers has no problem forwarding the MOTD from a server using `ping_passthrough`, but won't display it when running natively.

SubServers hasn't had any other issues related to the new hex color codes. I also confirmed that SubServers' possible MOTD suggestions and overrides are not the cause of this issue by testing with both `ProxyPingEvent` listeners completely removed.

**Comment by ME1312** [comment]
It seems the dev has given this issue the good ol' *"wtf is subservers lol i'm not fixing this"* treatment, even going as far as locking the thread, which is pretty unfortunate. Such are the things I have to deal with as a niche software developer.

&gt;MiniMOTD emits proper json
I find this quote to be particularly hilarious considering the problem is that it isn't actually emitting any JSON, but whatever.

The last thing I had to check for was some dependency versioning issues, but as expected, there's no problem there. Looks like we'll be filing this one under unsolved mysteries for the time being.

**Comment by wysohn** [comment]
I may have to fork my own version then :(

Thank you for the investigation!
