### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by skedgywasedgy** [ME1312/SubServers-2#61]
Sorry this isn't really the correct way to report this but I don't know where else to contact you. Your website recently went down and now either times out or sends me to the namecheap default page. I'm unable to access the Jenkins page or download the API. Without access to the API I essentially can't do anything with SubServers so I'm wondering if the website will return any time soon?

**Comment by Alex1607** [comment]
For now you could probably compile it yourself and work with that until the website is back up :D

**Comment by ME1312** [comment]
~~*Dang, I could have had this resolved 2 days ago. I'm slacking.*~~

Sorry for the downtime.
