### ISSUE TITLE
Replacement not working

### ISSUE THREAD

**Issue by SwordOfSouls** [ME1312/SubServers-2#62]
### Platform Information
These are the platforms and versions that are running SubServers.Bungee:
21:53:01 [INFO]   Windows 10 (19041.1052) [x64],
21:53:01 [INFO]   Java 16.0.1 [x64],
21:53:01 [INFO]   BungeeCord git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:a25c2b3:1584,
21:53:01 [INFO]   SubServers.Bungee v2.17.1a (21w27b)
21:53:01 [INFO]
21:53:02 [INFO] You are on the latest version.

### What Happened
Replacement doesn't work

### How It Happened
I tried to replace a txt file

### Additional Information
This is my template.yml:
`Version: '2.16a+'
Template:
  Enabled: true
  Icon: 'skeleton_skull'
  Replace:
    - '/server.properties'
    - '/plugins/CommandSync/config.txt'
  Settings:
    Executable: 'java -Xmx1024M -Dorg.bukkit.craftbukkit.libs.jline.terminal=none -Djansi.passthrough=true -jar Spigot.jar nogui'`
But when i run it I still get this:
SubServers::port in the config.

**Comment by ME1312** [comment]
Hi. It looks like your `template.yml` is missing the `Build` section, to which the `Replace` property belongs. Take a closer look at how [the file looks with all properties populated](https://github.com/ME1312/SubServers-2/wiki/SubCreator#templateyml) to see where to place them.
