### ISSUE TITLE
Disable server auto shutdown

### ISSUE THREAD

**Issue by wildmaster84** [ME1312/SubServers-2#65]
### What Should Be Added
an option to disable the auto server shutdown

### Why It Should be Added
it makes starting a server impossible

### What's The Alternative
start the server with no plugins

**Comment by ME1312** [comment]
What are you talking about? This isn't a thing.

**Comment by wildmaster84** [comment]
Yes it is? Any server i make automatically shuts down if no one is online and i want to disable it

**Comment by ME1312** [comment]
No it isn't? That feature doesn't exist. We don't do that here.

**Comment by wildmaster84** [comment]
Then what would cause that to happen?

**Comment by ME1312** [comment]
Well, the client plugin will actually check to make sure the server was supposed to have started, and shut you down should that not be the case. Make sure that the server is being linked to the right object in the server manager. You might just have a mismatch in that regard.

**Comment by wildmaster84** [comment]
I've made sure everything was correct but im still having the issue

**Comment by wildmaster84** [comment]
![image](https://user-images.githubusercontent.com/46942741/124682138-15f97f80-de98-11eb-98c6-0e14db86dbbb.png)

**Comment by ME1312** [comment]
I think it's safe to say that that one is not caused by SubServers. We always log the following message before stopping:
```
SubData > Received shutdown signal: blah blah blah... reasons
```
