### ISSUE TITLE
Feature Request: Expanded Placeholders

### ISSUE THREAD

**Issue by morgan2233** [ME1312/SubServers-2#69]
### What Should Be Added
I would like to see the ability to use sub server template placeholder (such as the exciting "SubServers::name") in other template files, primarily Plugin config files

### Why It Should be Added
I believe this should be added as with the increased number of bungee compatible plugins requiring the name of the server to be entered into the plugin config (for example LuckPerms), it would be ideal, easier and simpler for everyone who wishes to have ready-made server templates if the name was automatically set instead of after having made a new server from a template, having to stop it, manually open FTP or cli nano/vi and edit followed by starting again.

### What's The Alternative
The only alternative to mind is doing it by hand which is time consuming, repetitive and if you have multiple plugins can be confusing to remember which need their name changed and which don't.

**Comment by ME1312** [comment]
This feature exists, but with the exception of `/server.properties` you are required to specify which files need replacements. See the [`Replace` build option](https://github.com/ME1312/SubServers-2/wiki/SubCreator#templateyml) and its accompanying [file selection format](https://github.com/ME1312/SubServers-2/wiki/SubCreator#using-variables-in-other-files).
