### ISSUE TITLE
Feature Request: Template Overwrite Jar files

### ISSUE THREAD

**Issue by morgan2233** [ME1312/SubServers-2#70]
### What Should Be Added
I would like the option when executing the `sub update` command to have the jar files in the template to overwrite the existing jar files in the server (could be limited by last modified date as well).

### Why It Should be Added
I think this should be added as if you have a group of servers, for example, a hub group and suddenly a plugin receives an update; instead of manually updating each server you could run for example update the plugin in the template folder and then run `sub update :hubs [version]` to update that plugin in all the servers at once.

Alternatively, there could be a new command to search a specified server or group and replace the file/plugin and make it independent from the update command.

### What's The Alternative
The only current method is to do it by hand which is time-consuming when you have multiple servers (which is kinda the idea behind SubServers).

**Comment by ME1312** [comment]
There is a [build option called `Update-Files`](https://github.com/ME1312/SubServers-2/wiki/SubCreator#templateyml) which can do this for you. This rule applies to all (present) files though &ndash; not just jarfiles &ndash; so if something more specific is needed, let me know.
