### ISSUE TITLE
Feature Request: add getTemplates to subAPI.

### ISSUE THREAD

**Issue by alixplayz** [ME1312/SubServers-2#73]
### What Should Be Added
I would really like to see something like subAPI.getTemplates to get a list of all the subserver templates there all.

### Why It Should be Added
In my case I need to make a custom gui to start servers with specific templates. With getTemplates I could automatically add new templates to the gui without doing any modifying with the code.

### What's The Alternative
Every time I want to add a new server/event to the gui, I have to go in and manually change the gui to add that.

**Comment by ME1312** [comment]
`ServerTemplate` objects belong to the `SubCreator` instance of a `Host`. Once you get your hands on one, you will find that [that method already exists](https://dev.me1312.net/jenkins/job/SubServers%20Platform/javadoc/SubServers.Bungee/net/ME1312/SubServers/Bungee/Host/SubCreator.html#getTemplates--).

**Comment by alixplayz** [comment]
How exactly would I call that from a Spigot Server running the SubServers.Client API?

**Comment by ME1312** [comment]
By calling [this one instead](https://dev.me1312.net/jenkins/job/SubServers%20Platform/javadoc/SubServers.Client.Common/net/ME1312/SubServers/Client/Common/Network/API/SubCreator.html#getTemplates--).
