### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by BasToTheMax** [ME1312/SubServers-2#77]
Hello!

If I set `Restricted` to `true` in a server in `servers.yml`, what permission do I need to give the player to let them join the server?

**Comment by ME1312** [comment]
To join a restricted server, a player must exist in the [dynamic whitelist](https://dev.me1312.net/jenkins/job/SubServers%20Platform/javadoc/SubServers.Bungee/net/ME1312/SubServers/Bungee/Host/Server.html#whitelist-java.util.UUID-) or have the permission `bungeecord.server.<server>`.
