### ISSUE TITLE
Feature request: Synced folder

### ISSUE THREAD

**Issue by ghost** [ME1312/SubServers-2#8]
Hey, can you add a folder called 'sync' or something like that, so that files and folders you put in there, will be synced to all servers. Just like a symbolic link. 
There are many plugins on my servers that need to have the same config all the time, and it's a pain to edit 20+ configs instead of just 2.

For example:
If I edit /sync/plugins/WorldEdit/config.yml
the file will be changed as well in:
/Lobby/plugins/WorldEdit/config.yml
/Factions/plugins/WorldEdit/config.yml
and so on...

And when I delete /sync/WorldEdit/ and /sync/WorldEdit.jar, they will be deleted on all SubServers.

Can you make that possible? Thank you in advance

EDIT: I know the templates, however they only work when I generate a new server ;)

**Comment by ME1312** [comment]
This can be accomplished using applications that will probably do this feature _way_ better than I could have dreamed it to be.

**Comment by Patrick15a** [comment]
@DynamicThijs use on Windows the shortcut function or on linux the softlink function `ln -d -s configs-folder-path plugins-folder-path` like this: `ln -d -s ~/global-configs/* ~/Server/plugins/` (i think).
But when you delete a plugin or config you must delete the shortcut/softlink in every plugins folder.

On Mac i don't know how it works.
