### ISSUE TITLE
java.lang.IllegalStateException: There are no lang options available at this time - in SubServers-Client-Bukkit after creating a new Server

### ISSUE THREAD

**Issue by Patrick15a** [ME1312/SubServers-2#9]
OS: Linux - Debian 8 (jessie)
BungeCord Version: git:BungeeCord-Bootstrap:1.12-SNAPSHOT:4db5352:1235
Lobby Server Version: Spigot 1.11.2
Lobby Server Plugins: TitleManager v2.0.6
SubServer Version: 2.11.2l
SubServer-Client-Bukkit Version: 2.11.2g (istalled from creator)
Java Version:
```
root@vps3:~# java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
- ~/SubServers/[config.yml](http://short.myfilehost.de/0PgjV)

1. created a new Server named "Lobby" with `sub create Lobby ~ spigot 1.11.2 25010 1024`.
2. after the server was created I used `sub cmd Lobby op Patrick15a` in Console
3. than I used `/sub help` on the Lobby Server. And i got the following exception.

Chat:
`/sub help`

Console:
```
13:56:07 [INFO] Lobby > Patrick15a issued server command: /sub help
13:56:07 [WARNING] Lobby > java.lang.IllegalStateException: There are no lang options available at this time
13:56:07 [WARNING] Lobby > at net.ME1312.SubServers.Client.Bukkit.SubCommand.onCommand(SubCommand.java:33)
13:56:07 [WARNING] Lobby > at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
13:56:07 [WARNING] Lobby > at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
13:56:07 [WARNING] Lobby > at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
13:56:07 [WARNING] Lobby > at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13:56:07 [WARNING] Lobby > at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
13:56:07 [WARNING] Lobby > at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
13:56:07 [WARNING] Lobby > at java.lang.Thread.run(Thread.java:748)
```

**Comment by Patrick15a** [comment]
ops now i see the same issues in another issues post.

Sorry :*

**Comment by Patrick15a** [comment]
when i create a new SubServer i got first this exeption:
```
14:34:24 [INFO] ~/Creator > Generating Server Files...
14:34:24 [SEVERE] java.io.IOException: No such file or directory
14:34:24 [SEVERE]     at java.io.UnixFileSystem.createFileExclusively(Native Method)
14:34:24 [SEVERE]     at java.io.File.createNewFile(File.java:1012)
14:34:24 [SEVERE]     at net.ME1312.SubServers.Bungee.Library.Config.YAMLConfig.save(YAMLConfig.java:75)
14:34:24 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubCreator.generateClient(InternalSubCreator.java:270)
14:34:24 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubCreator.run(InternalSubCreator.java:64)
14:34:24 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubCreator.lambda$create$0(InternalSubCreator.java:212)
14:34:24 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
14:34:24 [INFO] ~/Creator > Launching build.sh
14:34:24 [INFO] ~/Creator > Downloading Buildtools...
...
```

**Comment by ME1312** [comment]
Continuing the thread #6 I see. Since you gave me everything I need to know already, let's pick up from where we were.

What are the permissions on this folder:
~Lobby/plugins

**Comment by Patrick15a** [comment]
~/Lobby/plugins (755) owned by the right user.

**Comment by Patrick15a** [comment]
I have found the fault...
The SubServer Creator has not defined the name for the SubData Service in 
~/Lobby/plugins/SubServers-Client-Bukkit/[config.yml](http://short.myfilehost.de/g4R7x)

After I change that to "Lobby" the commands works.

**Comment by ME1312** [comment]
That is true, however the why is the problem here. It remains that SubCreator cannot create the folder for config.yml, therefore it cannot create config.yml in some linux setups. The one seen there afterwards is the default one generated by SubServers.Client itself.

I will soon rewrite SubCreator, since I'd like to make better use of the templates folder as per requests. I hope to be rid of this bug as well, so I will use a different method of generating this file in the future.

**Comment by Patrick15a** [comment]
Ok. Thanks 👍

**Comment by ME1312** [comment]
Alright then, the latest [beta update](https://github.com/ME1312/SubServers-2/tree/master/Artifacts) has the SubCreator changes in it. I do hope the configuration works as intended this time around.

Also, you should delete (or rename) the Templates folder before installing this update.

**Comment by Patrick15a** [comment]
Thanks. It works.
You will receive a little donation from me :)
